# `home` is the primary home world. `home_nether` is a mirror of
# `home`, meaning it contains the same top-level
# claims. `home_the_end` is treated separately.
Worlds:
  home: {}
  home_nether:
    mirror: home
  home_the_end:
    ClaimMargin: 400
    ClaimBlockCost: 0.5
    InitialClaimSize: 32
    InitialClaimCost: 2000.0
    SecondaryClaimSize: 32
    SecondaryClaimCost: 2000.0
    ClaimAbandonCooldown: 1440
# Default World settings
ClaimMargin: 800 # Minimum distance between old and new claims
HomeMargin: 64 # Minimum distance between old and new homes
WildCooldown: 10 # In seconds
ClaimBlockCost: 0.1 # Cost per claim block
ManageGameMode: true # Set survival or adventure GameMode in home world
InitialClaimSize: 128 # Length of new claims
InitialClaimCost: -1.0 # Flat cost for initial claim
SecondaryClaimSize: 32 # Length of additional claims
SecondaryClaimCost: 2000.0 # Flat cost for additional claims
ClaimAbandonCooldown: 10 # In Minutes