name: Home
description: Manage the Home world. Users need to find a place to build, make a claim, set a home, and live in it.
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.cavetale.home.HomePlugin
depend: [ SQL ]
softdepend: []
commands:
  homeadmin:
    aliases: [ claimadmin ]
    description: Admin command
    permisson: home.admin
    usage: |-
      /homeadmin claims - list claims
      /homeadmin ignore - ignore claims
      /homeadmin reload - db and config
      /homeadmin debug - debug spam
      /homeadmin giveclaimblocks - Give blocks to claim
      /homeadmin giveallclaimblocks - Give blocks to all claims
      /homeadmin deleteclaim - Delete claim
  home:
    aliases: []
    description: Go to your primary home
    permission: home.home
    usage: |-
      /home - Visit your primary home
      /home NAME - Visit a named home
  homes:
    aliases: []
    description: Homes menu.
    permission: home.home
    usage: |-
      /homes - View the homes menu
      /homes set [name] - Set a home
      /homes invite <player> [name] - Allow someone to use your home
      /homes public <name> [alias] - Make a home public
      /homes delete [name] - delete a home
  sethome:
    aliases: []
    description: Set or reset a home
    permission: home.home
    usage: |-
      /sethome - Set your primary home
      /sethome NAME - Set a named home
  invitehome:
    aliases: []
    description: Invite someone to your home
    permission: home.home
    usage: |-
      /invitehome PLAYER - Invite to primary home
      /invitehome PLAYER NAME - Invite to named home
  visit:
    aliases: []
    description: Visit a public home
    permission: home.visit
    usage: |
  claim:
    aliases: [ c, cl, claims ]
    description: Manage your claims.
    permission: home.claim
    usage: |-
      /claim - View your claim options
      /claim new - Make a claim here
      /claim info - View claim info
      /claim home [id] - Teleport to claim
      /claim buy - Buy new claim blocks
      /claim add <player> - Add a member
      /claim invite <player> - Add visitor
      /claim remove <player> - Remove member or visitor
      /claim set - View or edit claim settings
      /claim grow - Grow claim to your location
      /claim shrink - Grow claim to your location
      /claim abandon - Abandon your claim
  build:
    aliases: [ wild ]
    description: Find a place to build.
    permission: home.build
    usage: /build - Find a place to build.
permissions:
  home.home:
    description: Use homes
    default: op
  home.claim:
    description: Use claims
    default: op
  home.visit:
    description: Visit public homes
    default: op
  home.build:
    description: Use /build
    default: op
  home.admin:
    description: Use /homeadmin
    default: op
