name: Home
description: Manage the Home world. Users need to find a place to build, make a claim, set a home, and live in it.
author: StarTux
version: 0.1
api-version: 1.17
website: https://cavetale.com
main: com.cavetale.home.HomePlugin
depend: [Core, SQL, Exploits, PlayerCache, Money, Perm, Connect, Sidebar]
softdepend: [dynmap, MagicMap, PlayerInfo]
commands:

  homeadmin:
    aliases: [homeadm, ha]
    description: Home Admin Commands
    permission: home.admin
    usage: /homeadmin

  claimadmin:
    aliases: [claimadmin, ca]
    description: Claim Admin Commands
    permission: home.admin
    usage: /claimadmin

  home:
    aliases: []
    description: Go to your primary home
    permission: home.home
    usage: |-
      /home - Visit your primary home
      /home NAME - Visit a named home

  homes:
    aliases: []
    description: Homes menu.
    permission: home.home
    usage: |-
      /homes - View the homes menu
      /homes set [name] - Set a home
      /homes invite <player> [name] - Allow someone to use your home
      /homes public <name> [alias] - Make a home public
      /homes delete [name] - delete a home

  listhomes:
    aliases: []
    description: List your homes
    permission: home.home
    usage: /listhomes

  sethome:
    aliases: []
    description: Set or reset a home
    permission: home.home
    usage: |-
      /sethome - Set your primary home
      /sethome NAME - Set a named home

  invitehome:
    aliases: []
    description: Invite someone to your home
    permission: home.home
    usage: /invitehome <player> [home]

  uninvitehome:
    aliases: []
    description: Invite someone to your home
    permission: home.home
    usage: /invitehome <player> [home]

  visit:
    aliases: []
    description: Visit a public home
    permission: home.visit
    usage: |-
      /visit - Public home menu.
      /visit [name] - Visit public home.

  claim:
    aliases: [c, cl, claims]
    description: Manage your claims.
    permission: home.claim
    usage: |-
      /claim - View your claim options
      /claim new - Make a claim here
      /claim info - View claim info
      /claim port [id] - Teleport to claim
      /claim buy - Buy new claim blocks
      /claim add <player> - Add a member
      /claim invite <player> - Add visitor
      /claim remove <player> - Remove member or visitor
      /claim set - View or edit claim settings
      /claim grow - Grow claim to your location
      /claim shrink - Grow claim to your location
      /claim abandon - Abandon your claim

  subclaim:
    aliases: []
    description: Subclaim management
    permission: home.claim
    usage: /subclaim

  wild:
    aliases: [build]
    description: Find a place to build.
    permission: home.build
    usage: /wild - Find a place to build.

permissions:
  home.home:
    description: Use homes
    default: op
  home.claim:
    description: Use claims
    default: op
  home.visit:
    description: Visit public homes
    default: op
  home.build:
    description: Use /build
    default: op
  home.admin:
    description: Use /homeadmin
    default: op
  home.adminclaims:
    description: Own all admin claims
    default: false
